Add missing dependencies for Ubuntu systems
Fixes this error:

error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1